macOS上的Java
GlobeMC/crashmc.com pull request #119
Opened 2023-08-14 10:32 UTC by hejiehao

2023-08-14 11:03 UTC, bingxin666 requested changes

2023-08-14 11:03 UTC, bingxin666 commented on docs/client/system.md
> +### 在 macOS 上的Java
漏空格了...

2023-08-14 11:09 UTC, bingxin666 approved these changes
我过了，再来个人帮忙查下

2023-08-14 13:35 UTC, zyxkad commented
所以，为什么不直接上Java官网链接，macos windows和linux的版本都有...

2023-08-14 13:39 UTC, zyxkad commented
> 给个链接？

hmm 文档里其他地方有写, 不确定这是否是macos独有问题，如果是那就随便吧（

2023-08-14 13:40 UTC, hejiehao commented
> > 给个链接？
> 
> hmm 文档里其他地方有写, 不确定这是否是macos独有问题，如果是那就随便吧（

应该是macOS独有的问题

2023-08-14 13:41 UTC, zyxkad commented
等一下，你的commit太乱了

2023-08-14 13:42 UTC, zyxkad commented
用`git reset --mixed origin/main`之后再commit, 别用merge

2023-08-16 14:21 UTC, closed without merging

2023-08-16 14:21 UTC, hejiehao commented
不一定是Java的问题