添加由防火墙或防病毒软件引起的崩溃问题
GlobeMC/crashmc.com pull request #124
Opened 2023-08-15 04:38 UTC by WForst-Breeze

解决方法参考了 [MC-34749](https://bugs.mojang.com/browse/MC-34749) 中 Mojang 官方及评论区 June Hanabi 提及的解决方案。

2023-08-15 04:41 UTC, zyxkad commented on docs/client/vanilla.md
> +7. 以管理员身份打开终端，**依次**输入以下命令后重启计算机：
终端是指cmd.exe还是powershell.exe, 建议写清楚

2023-08-15 04:43 UTC, zyxkad approved these changes

2023-08-15 04:43 UTC, zyxkad commented on docs/client/vanilla.md
> +1. 如您安装了 Avast，尝试重新安装 Avast 并重启。
重启是重启游戏 / Avast / 电脑?

2023-08-15 04:47 UTC, zyxkad requested changes

2023-08-15 04:47 UTC, zyxkad commented on docs/client/vanilla.md
> +1. 如您安装了 Avast，尝试重新安装 Avast 并重启。
重启是重启游戏 / Avast / 电脑?

2023-08-15 04:48 UTC, bingxin666 commented on docs/client/vanilla.md
> +7. 以管理员身份打开终端，**依次**输入以下命令后重启计算机：
有没有可能是terminal.exe(

2023-08-15 04:49 UTC, zyxkad commented on docs/client/vanilla.md
> +7. 以管理员身份打开终端，**依次**输入以下命令后重启计算机：
windows我记得没有叫terminal的（

2023-08-15 04:50 UTC, bingxin666 requested changes

2023-08-15 04:50 UTC, bingxin666 commented on docs/client/vanilla.md
> +1. 如您安装了 Avast，尝试重新安装 Avast 并重启。
指明重启对象

2023-08-15 04:51 UTC, bingxin666 commented on docs/client/vanilla.md
> +7. 以管理员身份打开终端，**依次**输入以下命令后重启计算机：
安装 2023 年 5 月 23 日更新 KB5026435 后，在所有版本的 Windows 11 和 Windows 10 22H2 版本中均可使用Terminal
所以这个说法没错（？

2023-08-15 05:11 UTC, youzi-2333 requested changes

2023-08-15 05:11 UTC, youzi-2333 commented on docs/client/vanilla.md
> +7. 以管理员身份打开 cmd.exe，**依次**输入以下命令后重启计算机：
打开 cmd 的步骤最好说清楚，即按下 `Win + R`，输入 `cmd`，点击 `确定`。
另外 cmd.exe 可以打个反引号，写成 `cmd.exe`……

2023-08-15 06:57 UTC, Big-Cake-jpg requested changes

2023-08-15 06:57 UTC, Big-Cake-jpg commented on docs/client/vanilla.md
> +> 以下命令将重置您的 WINSOCK、IPV4、IPV6 网络。
这里可以尝试使用 VitePress 的警告 container。
```suggestion
::: warning 警告
以下命令将重置您的 WINSOCK、IPV4、IPV6 网络。
:::
```

2023-08-15 13:45 UTC, XieXiLin2 commented on docs/client/vanilla.md
> +```
可标注代码使用的语言。
```suggestion
```bat
```

2023-08-15 15:09 UTC, WForst-Breeze commented
一般情况下，依照上方操作可以大概率解决该问题，但我注意到了在 [MC-34749](https://bugs.mojang.com/browse/MC-34749) 中，June Hanabi 依照亲身经历（他个人就是使用 Mojang 官方的方案但效果并不显著）提到了一些无法完全解决该问题或者说迫不得已的临时解决方案：

> - Open your minecraft game folder, often named .minecraft and close the launcher and any game instances
> - Delete these folders. If some don't exist that's fine: assets, bin, libraries, versions, webcache, config, defaultconfigs, usercache.json, usernamecache.json
> - If you're using forge, you'd need to re-download and re-install it otherwise for official versions let the launcher do that for you.
> 
> I often found I got one to two tries successfully everytime before it began messing up.
> 
> - Sometimes you can keep re-trying to open the world, I found it has a big chance of opening correctly the second time but begins to get more and more difficult to open subsequent times often requiring more continual tries before it just becomes nigh impossible to open.

是否有必要添加？以上这些方法都是临时性的，而无法彻底解决问题。

2023-08-16 07:38 UTC, Big-Cake-jpg requested changes

2023-08-16 07:38 UTC, Big-Cake-jpg commented on docs/client/vanilla.md
> +以下命令将重置您的 WINSOCK、IPV4、IPV6 网络。
使用正确的专有名词。
```suggestion
以下命令将重置您的 WINSOCK、IPv4、IPv6 网络。
```

2023-08-16 15:14 UTC, WForst-Breeze commented on docs/client/vanilla.md
> +<LauncherBadge type="bakaxl" text="BakaXL" />：向下滑动页面 -> `本体设置` -> `游戏目录` -> `可读写的 Minecraft 实例目录` -> 当前版本所在的游戏文件夹右侧的定位按钮
事实上，此处表述 “向下滑动页面” 并不严谨，实际操作中应为向上滑动，但考虑到如果表述为后者，一般第一反应会觉得是应该将页面向上翻（即向下滑动），所以这里还是采取了此表述。

不过这些小细节应该问题不大（）

2023-08-16 15:16 UTC, zyxkad commented on docs/client/vanilla.md
> +<LauncherBadge type="bakaxl" text="BakaXL" />：向下滑动页面 -> `本体设置` -> `游戏目录` -> `可读写的 Minecraft 实例目录` -> 当前版本所在的游戏文件夹右侧的定位按钮
> 此处表述 “向下滑动页面” 并不严谨

啊这，如果你指用户操作那么滑动方向是可配置的，比如我的配置就是手往下滑就是往下翻

2023-08-17 00:50 UTC, WForst-Breeze commented on docs/client/vanilla.md
> +<LauncherBadge type="bakaxl" text="BakaXL" />：向下滑动页面 -> `本体设置` -> `游戏目录` -> `可读写的 Minecraft 实例目录` -> 当前版本所在的游戏文件夹右侧的定位按钮
原来是这样……！那待会我再改一下吧qwq

2023-08-17 15:18 UTC, bingxin666 approved these changes

2023-08-18 03:34 UTC, Big-Cake-jpg approved these changes

2023-08-18 03:34 UTC, merged