Update basis.md
GlobeMC/crashmc.com pull request #131
Opened 2023-08-17 04:16 UTC by zkitefly

2023-08-17 15:22 UTC, 2623684696 approved these changes

2023-08-17 15:24 UTC, 2623684696 requested changes
你改啊（

2023-08-17 15:53 UTC, bingxin666 approved these changes
_**~~是我的锅...不知道微软jdk支持linux和macos~~**_
可以先合并，不过后面肯定还是得要统一文档中java的下载地址

2023-08-17 16:29 UTC, zyxkad commented on docs/basis.md
> +若使用 HMCL 启动失败或启动时出现 JavaFX 缺失相关提示，请尝试在系统设置中卸载相关 Java，然后下载并安装 [微软 JDK（JDK 17 - x86_64）](https://docs.hmcl.net/downloads/windows/x86_64.html) 后再尝试启动。
> 我直接改成 https://www.microsoft.com/openjdk#:~:text=Download 得了（

为什么不放oracle的jdk🧐 <https://www.oracle.com/java/technologies/downloads/#java17>

2023-08-17 16:32 UTC, zyxkad requested changes

2023-08-17 16:32 UTC, zyxkad commented on docs/basis.md
> +若使用 HMCL 启动失败或启动时出现 JavaFX 缺失相关提示，请尝试在系统设置中卸载相关 Java，然后下载并安装 [微软 JDK](https://www.microsoft.com/openjdk#:~:text=Download) 后再尝试启动。
请直接链接到jdk17, 而不是让用户自己找:
<https://learn.microsoft.com/zh-cn/java/openjdk/download#openjdk-17>

2023-08-17 22:32 UTC, zkitefly commented on docs/basis.md
> +若使用 HMCL 启动失败或启动时出现 JavaFX 缺失相关提示，请尝试在系统设置中卸载相关 Java，然后下载并安装 [微软 JDK（JDK 17 - x86_64）](https://docs.hmcl.net/downloads/windows/x86_64.html) 后再尝试启动。
因为 hmcl 缺 java 的时候弹出来的就是微软 jdk

2023-08-18 00:29 UTC, bingxin666 approved these changes

2023-08-18 02:48 UTC, 2623684696 approved these changes

2023-08-18 02:49 UTC, merged