✨ feat(blog): create blog part
GlobeMC/crashmc.com pull request #284
Opened 2024-06-22 10:43 UTC by bingling-sama

Create blog part for publishing blog posts, still WIP.

- [x] Basic Post List
- [ ] CSS Style
- [ ] auto close sidebar (help needed)
- [ ] Something else...

2024-06-22 14:29 UTC, Big-Cake-jpg commented
目前看来还行，但是文章列表能不能做成卡片样式并且添加一个封面支持？比如做成类似 [Files App 文档](https://files.community) 里博客版块那样。
感觉现在只有一个标题有些过于简陋了

2024-06-22 14:29 UTC, Big-Cake-jpg approved these changes

2024-06-22 16:26 UTC, bingling-sama commented
做了一点点简陋的样式，等待完善，不过已经可以进入 Review 阶段了。

2024-06-23 05:26 UTC, bingxin666 approved these changes

2024-06-23 06:17 UTC, bingling-sama commented
改进了一下卡片样式，各位可以点击 Preview Link 看看效果，如果可以的话我就再检查一下其他细节开始最终 Review 了。

PS：卡片的长宽设置急需一些建议。

2024-06-23 06:20 UTC, zyxkad requested changes
https://deploy-preview-284--crashmc.netlify.app/blog/
<img width="288" alt="Screenshot 2024-06-23 at 00 19 50" src="https://github.com/GlobeMC/crashmc.com/assets/91082411/99572996-640f-425f-aa24-20378ae1bd92">
这个anchor有🤏问题

2024-06-23 06:24 UTC, bingling-sama commented
> https://deploy-preview-284--crashmc.netlify.app/blog/ <img alt="Screenshot 2024-06-23 at 00 19 50" width="288" src="https://private-user-images.githubusercontent.com/91082411/342034225-99572996-640f-425f-aa24-20378ae1bd92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMjM5NDQsIm5iZiI6MTcxOTEyMzY0NCwicGF0aCI6Ii85MTA4MjQxMS8zNDIwMzQyMjUtOTk1NzI5OTYtNjQwZi00MjVmLWFhMjQtMjAzNzhhZTFiZDkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDA2MjA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmOTE3NjY2OTNjN2JlNWY1ZTgxM2MzODA3YTM3MDdkNGFiYzNlMWMzNWRiMTNhOTZlMTRiOWQwMDVlNzRmMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gfvfzo0EpLvm9eK89d3Vup51srR1J20Q-QXe_b0L5DQ"> 这个anchor有🤏问题

不太懂怎么禁用，他是 Vitepress 弄上去的。因为 Excerpt 是直接用的 Vitepress 的接口，用 v-html 渲染的，所以会带上 Vitepress 的样式

2024-06-23 06:30 UTC, zyxkad requested changes

2024-06-23 06:30 UTC, zyxkad commented on .vitepress/theme/layouts/Posts.vue
> +</style>
```suggestion

.container .card .content >>> .header-anchor {
	display: none;
}
</style>
```

2024-06-23 06:30 UTC, bingling-sama commented
https://github.com/GlobeMC/crashmc.com/assets/65523047/a1a9d234-43bd-4924-b953-faee8308a5d2

加了个 scale(0.8)，看着海星？

2024-06-23 06:33 UTC, zyxkad commented
另外建议加一个padding-top

2024-06-23 06:34 UTC, bingling-sama commented on .vitepress/theme/layouts/Posts.vue
> +</style>
已解决：通过 transform: scale(0.8); 调整大小来避免元素溢出。

2024-06-23 06:35 UTC, bingling-sama commented
> 另外建议加一个padding-top，多余的字可以用`text-overflow: ellipses`样式省略掉

要加 padding-top 是指？

2024-06-23 06:37 UTC, zyxkad commented
> > 另外建议加一个padding-top，多余的字可以用`text-overflow: ellipses`样式省略掉
> 
> 要加 padding-top 是指？

虽然scale这个操作很难评，但是它确实同时解决了标题太靠近边框的问题

2024-06-23 06:39 UTC, bingling-sama commented
> > > 另外建议加一个padding-top，多余的字可以用`text-overflow: ellipses`样式省略掉
> > 
> > 
> > 要加 padding-top 是指？
> 
> 虽然scale这个操作很难评，但是它确实同时解决了标题太靠近边框的问题

毕竟 excerpt 展示的是渲染后的 markdown 内容，也不太方便把里面的样式全部重写。scale的话……能用就行（x

2024-06-23 06:41 UTC, zyxkad commented on .vitepress/theme/layouts/Posts.vue
> +</style>
> 已解决：通过 transform: scale(0.8); 调整大小来避免元素溢出。

我的建议还是直接把anchor隐藏，因为卡片里不应该出现anchor。  
anchor是用于上下文定位，如果要用anchor定位到卡片内的标题不如直接发卡片跳转过后的链接

2024-06-23 06:56 UTC, bingling-sama commented
我发现那段文字不是溢出了，是被 Vitepress 给截断了：
![image](https://github.com/GlobeMC/crashmc.com/assets/65523047/a7878026-8a81-4ebb-a26a-23d922f59ad5)

2024-06-23 07:13 UTC, zyxkad approved these changes

2024-06-23 07:21 UTC, merged