✨ feature: restruct  docs
GlobeMC/crashmc.com pull request #87
Opened 2023-08-04 09:43 UTC by bingling-sama

add file `basis.md`
provide some basic knowledge for zero-experience player to enhance their understanding of crash

2023-08-04 09:47 UTC, bingling-sama commented
- [ ] a multi-level toc
- [ ] seperated and detailed instruction
- [ ] a footer displaying post author

2023-08-04 09:57 UTC, hejiehao commented
We are Chinese. You can speak Chinese.

2023-08-04 09:59 UTC, bingling-sama commented
> 

actually, it's my personal habits to use English on Github. if that's annoying u, I'll switch to Mandarin.

2023-08-04 10:08 UTC, Seayay requested changes

2023-08-04 10:08 UTC, Seayay commented on docs/basis.md
> +> Minecraft这个游戏，各种BUG和解决方案如果写成一堆不重复的书，摞起来的厚度可以比姚明还高。（引用自[ DinnerBone 个人博客](https://www.cnblogs.com/Dinnerbone/p/12045117.html)）
请遵循 [中文文案排版指北](https://github.com/sparanoid/chinese-copywriting-guidelines/blob/master/README.zh-Hans.md)，在中英文之间增加空格

2023-08-04 10:08 UTC, Seayay commented on docs/basis.md
> +A：`Minecraft` 与您平时游玩的端游、页游、或是 `steam` 这种玩家平台上下载的游戏不同，它的初始定位是一款独立的单机游戏，再加上 `Minecraft` 特殊的开发技术栈，便出现了您需要自己去解决一些游戏错误甚至崩溃的情况。
请使用官方名称
steam --> Steam

2023-08-04 10:10 UTC, Big-Cake-jpg requested changes
以及，行内代码与正文分隔只需使用一个空格即可。

2023-08-04 10:10 UTC, Big-Cake-jpg commented on docs/basis.md
> +> Minecraft这个游戏，各种BUG和解决方案如果写成一堆不重复的书，摞起来的厚度可以比姚明还高。（引用自[ DinnerBone 个人博客](https://www.cnblogs.com/Dinnerbone/p/12045117.html)）
中英文字符间需要使用空格分隔。请参考中文文案排版指北。
```suggestion
> Minecraft 这个游戏，各种 Bug 和解决方案如果写成一堆不重复的书，摞起来的厚度可以比姚明还高。（引用自 [DinnerBone 个人博客](https://www.cnblogs.com/Dinnerbone/p/12045117.html)）
```

2023-08-04 10:10 UTC, Big-Cake-jpg commented on docs/basis.md
> +大部分时候， `Minecraft` 开发者们都会使用这些第三方启动器而不是使用官启，他们提供了更多的调试选项及错误输出为开发者解决问题提供方便。
全角标点符号后个人认为不应使用空格。

2023-08-04 10:10 UTC, Big-Cake-jpg commented on docs/basis.md
> +- Windows 记事簿（说实话 Windows10/11 的记事簿还是很好用的，如果你不想下载什么软件就用它吧）
使用官方称谓。
```suggestion
- Windows 记事本（说实话，Windows 10 / 11 的记事本还是很好用的，如果你不想下载什么软件就用它吧）
```

2023-08-04 10:12 UTC, Seayay commented on docs/basis.md
> +大部分时候， `Minecraft` 开发者们都会使用这些第三方启动器而不是使用官启，他们提供了更多的调试选项及错误输出为开发者解决问题提供方便。
> 全角标点符号后个人认为不应使用空格。

根据 [中文文案排版指北](https://github.com/sparanoid/chinese-copywriting-guidelines/blob/master/README.zh-Hans.md)，全角标点与其他字符之间不加空格。

详见[此处](https://github.com/sparanoid/chinese-copywriting-guidelines/blob/master/README.zh-Hans.md#%E5%85%A8%E8%A7%92%E6%A0%87%E7%82%B9%E4%B8%8E%E5%85%B6%E4%BB%96%E5%AD%97%E7%AC%A6%E4%B9%8B%E9%97%B4%E4%B8%8D%E5%8A%A0%E7%A9%BA%E6%A0%BC)

2023-08-04 10:15 UTC, Seayay requested changes

2023-08-04 10:15 UTC, Seayay commented on docs/basis.md
> +- Windows 记事簿（说实话, `Windows 10 / 11` 的记事簿还是很好用的，如果你不想下载什么软件就用它吧）
句中请使用全角符号

2023-08-04 10:19 UTC, bingling-sama commented on docs/basis.md
> +> Minecraft这个游戏，各种BUG和解决方案如果写成一堆不重复的书，摞起来的厚度可以比姚明还高。（引用自[ DinnerBone 个人博客](https://www.cnblogs.com/Dinnerbone/p/12045117.html)）
actually, that's a quote so i didnt notice it.

2023-08-04 10:20 UTC, Seayay approved these changes

2023-08-04 10:27 UTC, Big-Cake-jpg requested changes

2023-08-04 10:27 UTC, Big-Cake-jpg commented on docs/basis.md
> +> `Minecraft` 这个游戏，各种BUG和解决方案如果写成一堆不重复的书，摞起来的厚度可以比姚明还高。（引用自[ DinnerBone 个人博客](https://www.cnblogs.com/Dinnerbone/p/12045117.html)）
```suggestion
> `Minecraft` 这个游戏，各种 Bug 和解决方案如果写成一堆不重复的书，摞起来的厚度可以比姚明还高。（引用自 [DinnerBone 个人博客](https://www.cnblogs.com/Dinnerbone/p/12045117.html)）
```

2023-08-04 10:27 UTC, Big-Cake-jpg commented on docs/basis.md
> +- Windows 记事簿（说实话， `Windows 10 / 11` 的记事簿还是很好用的，如果你不想下载什么软件就用它吧）
```suggestion
- Windows 记事本（说实话， `Windows 10 / 11` 的记事本还是很好用的，如果你不想下载什么软件就用它吧）
```
简体中文版 Windows 下显示为 “记事本”。

2023-08-04 10:46 UTC, bingling-sama commented
> - [x] basic knowledge
> - [ ] a multi-level toc
> - [ ] seperated and detailed instruction
> - [x] ~~a footer displaying post author~~ (I'll move this to another pr)

about these two TODO:

I think in our future doc, the crash happens on `client` and `server` should be seperated into 2 sub dir. And we should refine the crash into more classes.

2023-08-04 10:49 UTC, Big-Cake-jpg submitted a review, later dismissed

2023-08-04 12:09 UTC, bwtx2023 commented
Agree. 

However, I still want to notify that this doc will face pupils, but not only adults. So I hope that you can make the doc easier to read and understand. 

In #91, the analyzer is almost done, and you needn't put much time on it. Though, if you still have some enhancements, welcome to open an issue and discuss with us. 

(Off topic)

For convenient communication, I hope that you can join our QQ group. If you like, 199271393 is the group number. 

Thanks. 

---

同意上述观点。

但是，我仍然想要提醒，这篇文档不仅面向成人，也要面向小学生。所以我希望您能让文档更加易读并易于理解。

在 #91 中，分析器差不多完工了，您不用在它身上投入太多时间。尽管如此，如果您仍然有一些改进建议，欢迎开一个 Issue 并且和我们讨论。

（无关话题）

为了方便交流，我希望您还是能加入我们的 QQ 群。如果您想，群号是 199271393。

感谢。

2023-08-04 12:36 UTC, bingling-sama commented
I see. I'll make it simpler and more detailed in the future.

2023-08-05 03:03 UTC, Seayay requested changes

2023-08-05 03:03 UTC, Seayay commented on docs/.vitepress/config.ts
> +                { text: "mod 问题", link: "/client/mods"},
大写 Mod

2023-08-05 03:03 UTC, Seayay commented on docs/client/mods.md
> +`Minecraft` 拥有庞大的玩家社区，也有许多的社区开发者制作 `mod` 为原版游戏增加扩展内容及玩法，但同时这也导致了许许多多的问题，这里列出部分常见的 `mod` 问题及解决方案。
大写

2023-08-05 03:03 UTC, Seayay commented on docs/client/mods.md
> +解决方案：排查重复的 Mod ，然后移除重复项直至只剩下一个该 Mod 文件。
全角符号与其他字符中间不添加空格

2023-08-05 08:02 UTC, merged